# Generated by Django 5.2.4 on 2025-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='auto_category',
            field=models.CharField(blank=True, help_text='Auto-detected category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Flag if suggestion is likely spam'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Sentiment polarity: -1 (negative) to 1 (positive)', null=True),
        ),
    ]
